@baseurl=https://weather-data-2.fly.dev
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NGI0MGUzNGQ1YWE0NjJiZWFiMmIwZDciLCJpYXQiOjE2OTIxMzkxNjIsImV4cCI6MTY5NDczMTE2MiwidHlwZSI6ImFjY2VzcyJ9.wZULuhJInONfPpHelEIfD8zoDAsR2B1pzt2SJvy_Dz0

//Create a user
POST {{baseurl}}/auth/register HTTP/1.1
Content-Type: application/json

{
    "name": "Group 2 - 2023",
    "email": "group2@unilorin.com",
    "password": "12345678@group2"
}

### Login a user
POST {{baseurl}}/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "group2@unilorin.com",
    "password": "12345678@group2"
}

### Register a station
POST {{baseurl}}/stations/create HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Group 2 Project"
}

### Update a station
PATCH {{baseurl}}/stations/64b29d3cd1ba3df15ff8b34b HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Station 24",
    "lang" : "665756645.3546545343454",
    "lat" : "0903756645.3546545343454"
}


### Get a station
GET {{baseurl}}/stations/64b29d3cd1ba3df15ff8b34b HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Station 24",
    "lang" : "665756645.3546545343454",
    "lat" : "0903756645.3546545343454"
}


### Get all stations
GET {{baseurl}}/stations HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}


### Generate a save weather data token
POST {{baseurl}}/auth/generate-token HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "days": "365",
    "type":"saveWeather",
    "stationId": "64dbfeb9b5b278740198eb25"
}


### Generate a live weather data token
POST {{baseurl}}/auth/generate-token HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "days": "7",
    "type":"liveWeather",
    "stationId": "64b35cb752e0b8cb078b3305"
}


### Save weather data
POST {{baseurl}}/weather/64b3fda109c5084b17e455bf?token=KQcfs7wzwS HTTP/1.1
Content-Type: application/json

{
    "bmpTemp": "800",
    "dhtTemp": "120",
    "humidity": "2000"
}


### GEt weather data
GET {{baseurl}}/weather/64b411d8829834e03c49fa40?limit=1&sort=desc HTTP/1.1
Content-Type: application/json

